-- liquibase formatted sql

-- changeset VTB209274:1748270039302-1
CREATE TABLE public.change_limits
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lim_id       BIGINT,
    tran_id      UUID,
    change_limit DOUBLE PRECISION,
    CONSTRAINT pk_change_limits PRIMARY KEY (id)
);

-- changeset VTB209274:1748270039302-2
CREATE TABLE public.limits
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       INTEGER,
    current_limit DOUBLE PRECISION,
    CONSTRAINT pk_limits PRIMARY KEY (id)
);

